version: '3.7'

services:

  python:
    container_name: server
    image: server
    build:
      context: .
      dockerfile: server.dockerfile
    ports:
      - "5000:5000"
    networks:
      - server-network
      
networks:
  server-network:
    driver: bridge
